#Class Preprocessing

This cell contains the preparation of the orginal data. Please skip it because the data is already prepared.

In [ ]:
import numpy as np 
import pandas as pd 
from scipy import io

class Preprocessing:

  def __init__(self):
    self.name = 'Preprocessing'

  def loading(self, path_activities_1, path_activities_2, path_sensors_1, path_sensors_2):
    activities_data = io.loadmat(path_activities_1)
    activities_data_S1 = pd.DataFrame(activities_data['activities_data'] ,\
                                      columns = ['year_day', 'week_day', 'start_time', 'activity_code', 'subcategory_index', 'end_time', 'indicator'])

    activities_data = io.loadmat(path_activities_2)
    activities_data_S2 = pd.DataFrame(activities_data['activities_data'] ,\
                                      columns = ['year_day', 'week_day', 'start_time', 'activity_code', 'subcategory_index', 'end_time', 'indicator'])


    sensors_data = io.loadmat(path_sensors_1)
    sensors_data_S1 = pd.DataFrame(sensors_data['sensor_data'])
    sensors_data_S1.columns = ['year_day', 'week_day', 'activation' ,'deactivation', 'interval', 'sensor_id', 'location' ,'type']

    sensors_data = io.loadmat(path_sensors_2)
    sensors_data_S2 = pd.DataFrame(sensors_data['sensor_data'])
    sensors_data_S2.columns = ['year_day', 'week_day', 'activation' ,'deactivation', 'interval', 'sensor_id', 'location' ,'type']

    return activities_data_S1, activities_data_S2, sensors_data_S1, sensors_data_S2

  def recognize_activity(self, t): 
    activity = -1 
    for inter_key in activites_interval.keys() :
      start =inter_key[0] 
      end =  inter_key[1] 
      if t < end and t > start  : 
        activity  = activites_interval[inter_key] 
        break 
    return activity

  def is_sensor_active(self, t): 
    act = 0 
    for i in range(len(start_int)) : 
      if t < end_int[i] and t > start_int[i] : 
        act = 1 
        break 
    return act 

  def data_processing(self, activities_data, sensors_data):
    global activites_interval
    global start_int
    global end_int
    sensor_id_t = sensors_data.sensor_id.unique()
    year_day_t = sensors_data.year_day.unique()
    for i in year_day_t[0:1]:
      data = pd.DataFrame(data = np.arange(0,3600*24,30) ) 
      data.columns = ['time']
      activities_data_t = activities_data[activities_data['year_day']==i]
      keys = activities_data_t['activity_code'].values 
      start = activities_data_t['start_time'].values
      end = activities_data_t['end_time'].values 
      activites_interval = {}
      for id , activity in enumerate(keys) : 
        activites_interval[(start[id] , end[id])] = activity
      data['year_day'] = pd.DataFrame(data = [i]*2880 ) 
      recognize_activity = self.recognize_activity 
      data['activity'] = data['time'].apply(recognize_activity)
      sensors_data_t = sensors_data[sensors_data['year_day']==i]
      for j in sensor_id_t:
        sensors_data_t_n = sensors_data_t[sensors_data_t['sensor_id']==j]
        start_int = sensors_data_t_n.activation.values 
        end_int = sensors_data_t_n.deactivation.values 
        is_sensor_active = self.is_sensor_active
        data['sensor_id_'+str(j)] = data.time.apply(is_sensor_active)
    
      Final_Data = data

    for i in year_day_t[1:]:
      data = pd.DataFrame(data = np.arange(0,3600*24,30) ) 
      data.columns = ['time']
      activities_data_t = activities_data[activities_data['year_day']==i]
      keys = activities_data_t['activity_code'].values 
      start = activities_data_t['start_time'].values
      end = activities_data_t['end_time'].values 
      activites_interval = {}
      for id , activity in enumerate(keys) : 
        activites_interval[(start[id] , end[id])] = activity
      data['year_day'] = pd.DataFrame(data = [i]*2880 )
      recognize_activity = self.recognize_activity 
      data['activity'] = data['time'].apply(recognize_activity)

      sensors_data_t = sensors_data[sensors_data['year_day']==i]
      for j in sensor_id_t:
        sensors_data_t_n = sensors_data_t[sensors_data_t['sensor_id']==j]
        start_int = sensors_data_t_n.activation.values 
        end_int = sensors_data_t_n.deactivation.values 
        is_sensor_active = self.is_sensor_active
        data['sensor_id_'+str(j)] = data.time.apply(is_sensor_active)
      
      new_data = [Final_Data,data]
      Final_Data = pd.concat(new_data, ignore_index= True)
    return Final_Data

  def change_labels(self, Final_Data):
    Final_Data.loc[Final_Data[Final_Data.activity.\
                                    isin([20.0,25.0,105.0,100.0,80.0,30.0,5.0,140.0,135.0,40.0,75.0])].index,'activity']=-1

    return Final_Data

  def remove_rows(self, Final_Data):
    Final_Data = Final_Data[Final_Data.activity != -1.0]
    return Final_Data

  def align_features(self, data_aligned, data_to_align):
    data_to_align = data_to_align.iloc[:,:data_aligned.shape[1]]
    return data_to_align




#script
path_activities_1 = 'activities_data1.mat'
path_activities_2 = 'activities_data2.mat'
path_sensors_1 = 'sensor_data1.mat'
path_sensors_2 = 'sensor_data2.mat'

preprocessing = Preprocessing()
activities_data_S2, activities_data_S1, sensors_data_S2, sensors_data_S1 = preprocessing.loading(path_activities_1,\
                                                                                                 path_activities_2, path_sensors_1, path_sensors_2)
Final_Data_S1 = preprocessing.data_processing(activities_data_S1, sensors_data_S1)
Final_Data_S2 = preprocessing.data_processing(activities_data_S2, sensors_data_S2)

Final_Data_S1 = preprocessing.change_labels(Final_Data_S1)
Final_Data_S2 = preprocessing.change_labels(Final_Data_S2)

Final_Data_S1 = preprocessing.remove_rows(Final_Data_S1)
Final_Data_S2 = preprocessing.remove_rows(Final_Data_S2)

#Final_Data_S2 = preprocessing.align_features(Final_Data_S1, Final_Data_S2)
  

#Import Data

In [ ]:
import pandas as pd 
Final_Data_S1 = pd.read_csv("/content/drive/MyDrive/Final_Data_S1_AR.csv")
Final_Data_S2 = pd.read_csv("/content/drive/MyDrive/Final_Data_S2_AR.csv")

#Class Transformation
We created a PCA-like transformation for the source and for the target datasets to transform the data into a new common feature space.

In [ ]:
import numpy as np 
import pandas as pd 
np.random.seed(2)

class Transformation:

  def remove_features(self, Final_Data):
    Final_Data = Final_Data.drop(['time', 'year_day'], axis = 1)
    return Final_Data

  def centered_data(self, data):
    for i in range(1,data.shape[1]):
      mean = data.iloc[:,i].mean()
      data.iloc[:,i] = data.iloc[:,i] - mean
    return data

  def Transoform_Data(self, data, X, n_pca, name, number_activity):

    data_prob = data.activity.value_counts()/len(data)
    indx_prob = {i:data_prob[i] for i in data_prob.index}

    initial_activity = pd.DataFrame(data = data.groupby('activity').cov().iloc[0:data.shape[1]-1]).index[0][0]
    cov = (data.groupby('activity').cov().iloc[0:data.shape[1]-1])*indx_prob[initial_activity]

    for i in range(data.shape[1]-1,number_activity*(data.shape[1]-1),data.shape[1]-1):
      next_activity = pd.DataFrame(data = data.groupby('activity').cov().iloc[i:i+data.shape[1]-1]).index[0][0]
      cov += (data.groupby('activity').cov().iloc[i:i+data.shape[1]-1].values)*indx_prob[next_activity]

    cov = pd.DataFrame(data = cov)
    eigenValues, eigenVectors = np.linalg.eig(cov)
    idx = eigenValues.argsort()[::-1]   
    eigenValues = eigenValues[idx]
    eigenVectors = eigenVectors[:,idx]

    
    Cov_Matrix = pd.DataFrame(data = eigenVectors).iloc[:,:n_pca]
    Columns = ['pc_'+name + '_' + str(i) for i in range(1,n_pca+1)]
    Cov_Matrix.columns = Columns


    normalized_Cov_Matrix=(Cov_Matrix-Cov_Matrix.min())/(Cov_Matrix.max()-Cov_Matrix.min())
    Transform_Matrix = Cov_Matrix.transpose()
    X = X.drop(['activity'], axis = 1).transpose()
    Final_Data = np.dot(Transform_Matrix, X)
    Final_Data = pd.DataFrame(data = Final_Data.transpose(), columns= Columns)

    return Final_Data

#script
transformation = Transformation()
Cov_Data_S1 = transformation.remove_features(Final_Data_S1)
Cov_Data_S2 = transformation.remove_features(Final_Data_S2)

#Cov_Data_S1 = transformation.centered_data(Cov_Data_S1)
#Cov_Data_S2 = transformation.centered_data(Cov_Data_S2)

Final_Data_Source = transformation.Transoform_Data(Cov_Data_S1, Cov_Data_S1, 10, 'Source',5)
Final_Data_Target = transformation.Transoform_Data(Cov_Data_S2, Cov_Data_S2, 9, 'Target',5)



#Class Divergence_Calculation
We calculated the divergence between features from source and target datasets using the JSD.

In [ ]:
import numpy as np 
import pandas as pd 
from scipy.spatial import distance

class Divergence_Calculation:

  def add_target(self, Final_Data, Cov_Data):
    Final_Data['activity'] = Cov_Data.activity.values
    return Final_Data

  def prob_dist_divergence_initial(self, data, num_pc, name):

    results = data
    column = ['pc_'+ name + '_' + str(i) for i in range(1,num_pc+1)]
    res = pd.DataFrame(data = np.zeros((5,1)), columns=['None'])
    
    for i in column:
      table = pd.DataFrame(data = np.zeros((5,5)), \
                           columns= [i+'15.0', i+'60.0', i+'65.0', i+'70.0', i+'85.0'])
      condit = pd.DataFrame(data = results.groupby('activity')[i])
      for j in range(5):
        x = condit.iloc[j,1]
        table.iloc[:,j] = np.histogram(x, bins = 5)[0] / len(x)   
      res = pd.concat([res, table], axis=1)

    return res

  
  def jsd_final(self, X1_Source_init,X2_Target_init, Final_Data_Target):

    target_prob = Final_Data_Target.activity.value_counts()/len(Final_Data_Target)
    matrix = pd.DataFrame(data = np.zeros((Final_Data_Source.shape[1]-1, Final_Data_Target.shape[1]-1)))
    matrix.columns = [i for i in Final_Data_Target.columns if i!= 'activity']
    matrix.index = [i for i in Final_Data_Source.columns if i != 'activity']
      
    for i in matrix.columns:
      for j in matrix.index:
        matrix.loc[j,i] = sum([target_prob.loc[target_prob.index == k].\
          values[0]*distance.jensenshannon(X1_Source_init[j+str(k)], X2_Target_init[i+str(k)], 2.0) for k in target_prob.index])
    return matrix

#script
divergence_calculation = Divergence_Calculation()
Final_Data_Source = divergence_calculation.add_target(Final_Data_Source, Cov_Data_S1)
Final_Data_Target = divergence_calculation.add_target(Final_Data_Target, Cov_Data_S2)

X1_Source_init = divergence_calculation.prob_dist_divergence_initial(Final_Data_Source, 10, 'Source')
X2_Target_init = divergence_calculation.prob_dist_divergence_initial(Final_Data_Target, 9, 'Target')

divergence_matrix = divergence_calculation.jsd_final(X1_Source_init,X2_Target_init, Final_Data_Target)



#Class PreMapping
We used Thresholidng to avoid negative transfer and we created the Preferences lists for the mapping procedure.

In [ ]:
import numpy as np 
import pandas as pd 

class PreMapping:

  def threshold_select(self, divergence_matrix, threshold):
    divergence_matrix_bool = divergence_matrix > threshold
    indx = []

    for j in range(divergence_matrix.shape[1]):
      Test = True
      for i in range(len(divergence_matrix)):
        if divergence_matrix_bool.iloc[i,j] == False:
          Test = False
      if Test == True:
        indx.append(j)

    new_indx = [i for i in range(divergence_matrix.shape[1]) if i not in indx]
    divergence_matrix = divergence_matrix.iloc[:,new_indx]
    return divergence_matrix

  def preferences(self, divergence_matrix):
    Source_features = [i for i in divergence_matrix.index]
    Target_features = [i for i in divergence_matrix.columns]

    priority_source = {i:list(divergence_matrix.loc[i,:].sort_values().index) for i in Source_features}
    priority_target = {i:list(divergence_matrix.loc[:,i].sort_values().index) for i in Target_features}

    return priority_source, priority_target

#script
preMapping = PreMapping()
#divergence_matrix = preMapping.threshold_select(divergence_matrix, 0.32)
priority_source, priority_target = preMapping.preferences(divergence_matrix)
  

#Class Mapping
We applied the Gale-Shapley Algorithm to map features from both domains based on their divergence values.

In [ ]:
import numpy as np 
import pandas as pd 
from collections import defaultdict
class Mapping:

    def __init__(self, men, women):
        '''
        Constructs a Matcher instance.
        Takes a dict of men's spousal preferences, `men`,
        and a dict of women's spousal preferences, `women`.
        '''
        self.M = men
        self.W = women
        self.wives = {}
        self.pairs = []

        # we index spousal preferences at initialization 
        # to avoid expensive lookups when matching
        self.mrank = defaultdict(dict)  # `mrank[m][w]` is m's ranking of w
        self.wrank = defaultdict(dict)  # `wrank[w][m]` is w's ranking of m

        for m, prefs in men.items():
            for i, w in enumerate(prefs):
                self.mrank[m][w] = i

        for w, prefs in women.items():
            for i, m in enumerate(prefs):
                self.wrank[w][m] = i


    def __call__(self):
        return self.match()

    def prefers(self, w, m, h):
        '''Test whether w prefers m over h.'''
        return self.wrank[w][m] < self.wrank[w][h]

    def after(self, m, w):
        '''Return the woman favored by m after w.'''
        i = self.mrank[m][w] + 1    # index of woman following w in list of prefs
        return self.M[m][i]

    def match(self, men=None, next=None, wives=None):
        '''
        Try to match all men with their next preferred spouse.
        
        '''
        if men is None: 
            men = self.M.keys()         # get the complete list of men
        if next is None: 
            # if not defined, map each man to their first preference
            next = dict((m, rank[0]) for m, rank in self.M.items()) 
        if wives is None: 
            wives = {}                  # mapping from women to current spouse
        if not len(men): 
            self.pairs = [(h, w) for w, h in wives.items()]
            self.wives = wives
            return wives
        m, men = list(men)[0], list(men)[1:]
        w = next[m]                     # next woman for m to propose to
        next[m] = self.after(m, w)      # woman after w in m's list of prefs
        if w in wives:
            h = wives[w]                # current husband
            if self.prefers(w, m, h):
                men.append(h)           # husband becomes available again
                wives[w] = m            # w becomes wife of m
            else:
                men.append(m)           # m remains unmarried
        else:
            wives[w] = m                # w becomes wife of m
        return self.match(men, next, wives)

    def map_source(self, Final_Data_Source, Final_Data_Target, Final_Match):

      Final_Data_Source = Final_Data_Source.rename(columns=Final_Match)
      Final_Data_Source = Final_Data_Source[Final_Data_Target.columns]
      return Final_Data_Source

#script
mapping = Mapping(priority_target, priority_source)
Final_Match = mapping.match()
Final_Data_Target = Final_Data_Target[list(Final_Match.values()) + ['activity']]
Final_Data_Source = mapping.map_source(Final_Data_Source, Final_Data_Target, Final_Match)

#Class PostMapping
We added target data in the training to enhance the performance of the model.

In [ ]:
import numpy as np 
import pandas as pd 

class PostMapping:

  def shuffle_data(self, Final_Data):
    Final_Data = Final_Data.sample(frac = 1)
    return Final_Data

  def rearrage_data(self, Final_Data_Source, Final_Data_Target, number_rows):
    add_data = Final_Data_Target.iloc[:number_rows,:]
    Final_Data_Target = Final_Data_Target.iloc[number_rows:,:]
    frames = [Final_Data_Source, add_data]
    Final_Data_Source = pd.concat(frames)

    return Final_Data_Source, Final_Data_Target


#script
postMapping = PostMapping()
Final_Data_Source = postMapping.shuffle_data(Final_Data_Source)
Final_Data_Target = postMapping.shuffle_data(Final_Data_Target)
Data_Target = Final_Data_Target
# Target data added in the training
# 0 days = 0
# 2 days = 488
# 4 days = 975
# 6 days = 1462
# 8 days = 1950
# 10 days = 2440

Final_Data_Source, Final_Data_Target = postMapping.rearrage_data(Final_Data_Source, Final_Data_Target, 2440 )


#Class Modeling

In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.metrics import precision_recall_fscore_support as score

class Modeling:

  def split_train_test(self, Final_Data_Source, Final_Data_Target):
    X_train = Final_Data_Source.drop(['activity'], axis=1)
    y_train = Final_Data_Source['activity']
    X_test = Final_Data_Target.drop(['activity'], axis=1)
    y_test = Final_Data_Target['activity']

    return X_train, y_train, X_test, y_test

  def split_train_val(self, X, y):    
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42)
    return X_train, X_val, y_train, y_val

  def pipelines_def(self):
    pipelines = []
    params = []
    names = []
    #Notice that we tried to balance the data via using the clf__class_weight parameter in the models

   
    pipelines.append(Pipeline([('clf', DecisionTreeClassifier())])) ## DecisionTreeClassifier
    params.append({'clf__max_features': [None], 'clf__min_samples_split': [2], 'clf__min_samples_leaf':[1],
                  'clf__class_weight': ['balanced']})
    names.append('DecisionTreeClassifier') 

  


    return pipelines, params, names

  def model(self, pipeline, param, name, X, y):    
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=32)

    grid_obj = GridSearchCV(estimator=pipeline, param_grid=param, cv=cv, scoring='f1_micro', n_jobs=-1)
    grid_obj.fit(X,y)  

    print(name, 'F1-measure:', grid_obj.best_score_)
    estimator = grid_obj.best_estimator_
    estimator.fit(X,y) # train on all training dataset
    return estimator 


  def estimators(self, pipelines, params, names,  X_train, y_train):
    estimators = []
    for idx in range(0,len(pipelines)):    
        estimators.append(self.model(pipelines[idx], params[idx], names[idx], X_train, y_train))
    return estimators


  def evaluate_models(self,estimators, names, X_test, y_test):
   
    for idx, estimator in enumerate(estimators):
      print('\nPerformance of', names[idx])
      y_pred = estimator.predict(X_test)       
      print('\nConfusion matrix\n', confusion_matrix(y_test, y_pred), '\n')    
      print('F1-measure', f1_score(y_test, y_pred, average='micro'), '\n')

      precision, recall, fscore, support = score(y_test, y_pred)

      print('precision: {}'.format(precision))
      print('recall: {}'.format(recall))
      print('fscore: {}'.format(fscore))
      print('support: {}'.format(support))

    return

#script
modeling = Modeling()

X_train, y_train, X_test, y_test = modeling.split_train_test(Final_Data_Source, Final_Data_Target)
X_test_T, y_test_T, X_test_T, y_test_T = modeling.split_train_test(Data_Target, Data_Target)
X_train_S,  X_test_S, y_train_S, y_test_S = modeling.split_train_val(X_test_T, y_test_T                                                                  
                                                                     )

pipelines, params, names = modeling.pipelines_def()
print('Source Training results_without TL')
estimators = modeling.estimators(pipelines, params, names, X_train_S, y_train_S)
print('Source Testing results_without TL')
modeling.evaluate_models(estimators, names, X_test_S, y_test_S)


print('Training results_TL')
estimators = modeling.estimators(pipelines, params, names, X_train, y_train)
print('Testing results_TL')
modeling.evaluate_models(estimators, names, X_test, y_test)

Source Training results_without TL
DecisionTreeClassifier F1-measure: 0.8521869835800431
Source Testing results_without TL

Performance of DecisionTreeClassifier

Confusion matrix
 [[324  26   7  15   7]
 [  6 121   2   0   2]
 [ 23  15 274   0  65]
 [  4   0   0  94   0]
 [  2   0   5   0  32]] 

F1-measure 0.8251953125 

precision: [0.90250696 0.74691358 0.95138889 0.86238532 0.30188679]
recall: [0.85488127 0.92366412 0.72679045 0.95918367 0.82051282]
fscore: [0.87804878 0.82593857 0.82406015 0.90821256 0.44137931]
support: [379 131 377  98  39]
Training results_TL
DecisionTreeClassifier F1-measure: 0.9123273844039257
Testing results_TL

Performance of DecisionTreeClassifier

Confusion matrix
 [[330  28   5  12   5]
 [  2 107   0   0   1]
 [ 13  15 321   0   4]
 [  5   0   0  89   0]
 [  1   0   7   0  27]] 

F1-measure 0.8991769547325102 

precision: [0.94017094 0.71333333 0.96396396 0.88118812 0.72972973]
recall: [0.86842105 0.97272727 0.90934844 0.94680851 0.77142857]
fscore: [0.9

In [ ]:
#Thank you